// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ5lMoizjR4kcvzY6G2iHiSeuHIs5wHLk',
    appId: '1:99477702564:web:2bd75fbdf23725484de331',
    messagingSenderId: '99477702564',
    projectId: 'mytodo-fe7bf',
    authDomain: 'mytodo-fe7bf.firebaseapp.com',
    storageBucket: 'mytodo-fe7bf.appspot.com',
    measurementId: 'G-CR5K8T7X06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBygmMiylDqkhSa1Sk0eaLKedA8cdPFI10',
    appId: '1:99477702564:android:544e2c513f6278124de331',
    messagingSenderId: '99477702564',
    projectId: 'mytodo-fe7bf',
    storageBucket: 'mytodo-fe7bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4IhMkNDS2ElRtyw89xC5f8AzO08PvxLc',
    appId: '1:99477702564:ios:69edd96793fd81ff4de331',
    messagingSenderId: '99477702564',
    projectId: 'mytodo-fe7bf',
    storageBucket: 'mytodo-fe7bf.appspot.com',
    iosBundleId: 'com.example.mytodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4IhMkNDS2ElRtyw89xC5f8AzO08PvxLc',
    appId: '1:99477702564:ios:df585007623b8dda4de331',
    messagingSenderId: '99477702564',
    projectId: 'mytodo-fe7bf',
    storageBucket: 'mytodo-fe7bf.appspot.com',
    iosBundleId: 'com.example.mytodo.RunnerTests',
  );
}
